version: '2.4'
volumes:
  ignition:
    ignition-data: {} 
   db:
    driver: local
services:
  ignition:
    image: 'inductiveautomation/ignition:latest'
    ports:
      - '9088:8088'
      - '8043:8043'
      - '8060:8060'
    cap_add:
      - SYS_RAWIO
    volumes:
      - 'ignition-data:/var/lib/ignition/data'
    privileged: true
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - ./data:/var/lib/postgresql/data